### ISSUE TITLE
Provide Docker image for easy setup

### ISSUE THREAD

**Issue by int128** [int128/kubelogin#206]
It may be possible to call the docker command from kubeconfig (i.e. the client-go credential plugin). It allows the authentication without binary installation and improves user experience, especially reduces administrators efforts.

## TODOs

- [x] Set up a Docker registry and automated build.
- [x] Design and implement.
- [x] Set up the release process.
  - [x] Automatically bump the version in https://github.com/int128/kubelogin-docker
- [ ] Add a document for onboarding

### User experience

Create the following kubeconfig to call the docker command.

```yaml
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: docker
      args:
      - run
      - -v
      - /tmp/.token-cache:/.token-cache
      - -p
      - 8000:8000
      - --rm
      - quay.io/int128/kubelogin:v1.16.0
      - get-token
      - --token-cache-dir=/.token-cache
      - --listen-address=0.0.0.0:8000
      - --oidc-issuer-url=https://accounts.google.com
```

Known limitations:
- It cannot open the browser automatically.
- The container port and listen port must be equal. This is required for consistency of the redirect URI.

### Technical concerns

~~It needs to add a feature to listen any address. This is required for access from outside of a container.~~ available in v1.16.0

It need to store a token cache to a volume. It may cause permission problems (on Linux).
